# Generated by Django 2.1 on 2018-08-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangerateapp', '0002_exchangerate_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency', 'date')},
        ),
    ]
