# Generated by Django 2.1 on 2018-08-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangerateapp', '0004_auto_20180804_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate_value',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
